export const TICKET_SEARCH_REQUEST = 'TICKET_SEARCH_REQUEST';
export const TICKET_SEARCH_SUCCESS = 'TICKET_SEARCH_SUCCESS';
export const TICKET_SEARCH_FAIL = 'TICKET_SEARCH_FAIL';
export const TICKET_CLEAR_SEARCH = 'TICKET_CLEAR_SEARCH';
