export const TECH_LIST_REQUEST = 'TECH_LIST_REQUEST';
export const TECH_LIST_SUCCESS = 'TECH_LIST_SUCCESS';
export const TECH_LIST_FAIL = 'TECH_LIST_FAIL';

export const TECH_DETAILS_REQUEST = 'TECH_DETAILS_REQUEST';
export const TECH_DETAILS_SUCCESS = 'TECH_DETAILS_SUCCESS';
export const TECH_DETAILS_RESET = 'TECH_DETAILS_RESET';
export const TECH_DETAILS_FAIL = 'TECH_DETAILS_FAIL';

export const TECH_ASSIGN_REQUEST = 'TECH_ASSIGN_REQUEST';
export const TECH_ASSIGN_SUCCESS = 'TECH_ASSIGN_SUCCESS';
export const TECH_ASSIGN_RESET = 'TECH_ASSIGN_RESET';
export const TECH_ASSIGN_FAIL = 'TECH_ASSIGN_FAIL';

// export const TECH_SINGLE_REQUEST = 'TECH_SINGLE_REQUEST';
// export const TECH_SINGLE_SUCCESS = 'TECH_SINGLE_SUCCESS';
// export const TECH_SINGLE_FAIL = 'TECH_SINGLE_FAIL';
// export const TECH_SINGLE_CLEAR = 'TECH_SINGLE_CLEAR';
