export const TICKET_LIST_REQUEST = 'TICKET_LIST_REQUEST';
export const TICKET_LIST_SUCCESS = 'TICKET_LIST_SUCCESS';
export const TICKET_LIST_FAIL = 'TICKET_LIST_FAIL';
export const TICKET_LIST_CLEAR = 'TICKET_LIST_CLEAR';

export const TICKET_SEARCH_DISABLE_REFRESH = 'TICKET_SEARCH_DISABLE_REFRESH';

export const TICKET_DETAILS_REQUEST = 'TICKET_DETAILS_REQUEST';
export const TICKET_DETAILS_SUCCESS = 'TICKET_DETAILS_SUCCESS';
export const TICKET_DETAILS_FAIL = 'TICKET_DETAILS_FAIL';
export const TICKET_CLEAR_CURRENT = 'TICKET_CLEAR_CURRENT';

export const TICKET_FILL_MYTICKETS_REQUEST = 'TICKET_FILL_MYTICKETS_REQUEST';
export const TICKET_FILL_MYTICKETS_SUCCESS = 'TICKET_FILL_MYTICKETS_SUCCESS';
export const TICKET_FILL_MYTICKETS_FAIL = 'TICKET_FILL_MYTICKETS_FAIL';
export const TICKET_FILL_MYTICKETS_CLEAR = 'TICKET_FILL_MYTICKETS_CLEAR';
export const MY_TICKET_STATUS = 'MY_TICKET_STATUS';

export const TICKET_CREATE_REQUEST = 'TICKET_CREATE_REQUEST';
export const TICKET_CREATE_SUCCESS = 'TICKET_CREATE_SUCCESS';
export const TICKET_CREATE_RESET = 'TICKET_CREATE_RESET';
export const TICKET_CREATE_FAIL = 'TICKET_CREATE_FAIL';
export const TICKET_CREATE_DISABLE_REFRESH = 'TICKET_CREATE_DISABLE_REFRESH';

export const TICKET_EDIT_REQUEST = 'TICKET_EDIT_REQUEST';
export const TICKET_EDIT_SUCCESS = 'TICKET_EDIT_SUCCESS';
export const TICKET_EDIT_RESET = 'TICKET_EDIT_RESET';
export const TICKET_EDIT_FAIL = 'TICKET_EDIT_FAIL';

export const TICKET_DELETE_REQUEST = 'TICKET_DELETE_REQUEST';
export const TICKET_DELETE_SUCCESS = 'TICKET_DELETE_SUCCESS';
export const TICKET_DELETE_FAIL = 'TICKET_DELETE_FAIL';
export const TICKET_DELETE_RESET = 'TICKET_DELETE_RESET';
